### PR TITLE
Gin middleware

### PR DESCRIPTION
**Pull request by ADone**
for #22

### CODE REVIEW

**Comment by rs** [comment]
I realize that it means adding a dep on Gin. I'd prefer not to add any dep. A Gin context can't be expressed as an interface so I'm not sure it would be possible.

**Comment by ADone** [comment]
I warned about this)
Is it possible to make a `preflight` and `actual` handlers public?

**Comment by ADone** [comment]
Then they can be called by separated gin-cors glue package

**Comment by rs** [comment]
That's certainly an option yes.

**Comment by rs** [comment]
And sorry about missing your warning. I overlooked it.

**Comment by tyranron** [comment]
> Is it possible to make a preflight and actual handlers public?

> That's certainly an option yes.

@rs will you accept PR for this? I'm quite interested in using this package with Gin smoothly.

**Comment by rs** [comment]
Sure if it does not add a dep on Gin

**Comment by tyranron** [comment]
@rs initial idea was only to make `handlePreflight()` and `handleActualRequest()` public.

But your mention pushed me to an idea.... what if put Gin wrapper into subpackage `github.com/rs/cors/wrapper/gin`? So anyone who uses `github.com/rs/cors` won't have a dep on Gin, and Gin users may just use `github.com/rs/cors/wrapper/gin`.

**Comment by rs** [comment]
That would work.

**Pull request closed without merging**
