### PR TITLE
Require Go 1.23.0 or above (fixes #187)

### LINKED ISSUE #187: Bump go directive
The go directive remains at 1.13, and [Go 1.13 dates back to 2019](https://go.dev/doc/devel/release#go1.13).

Recent versions of Go saw valuable additions, such as builtin `min` and `max` and the `slices` package, which would come in handy in rs/cors (try grepping the codebase for "TODO").

The go directive should be bumped to 1.22 or perhaps even 1.23. Doing so won't prevent dependents from using an older version of the library that relies on an older go directive.

### PR DESCRIPTION
**Pull request by jub0bs**

### CODE REVIEW

**Comment by rs** [comment]
I merged too fast. It seems like a mod file doesn't have the right format, can you please check?

**Comment by jub0bs** [comment]
@rs Are you referring to the root go.mod? What problem are you observing? Everything seems fine.

**Comment by rs** [comment]
Please check the CI result on main.

**Comment by jub0bs** [comment]
I remember running into that issue myself. A patch version in the `go` directive is allowed by the modules system but, for some reason, GitHub Actions seems to choke on it. I'll open another PR to rectify this.

**Comment by rs** [comment]
I think it just a an action configured specifically with this go version to ensure the code was backward compatible.

**Comment by jub0bs** [comment]
Yes, I think you're right. Using only 1.23 in the version matrix in `.github/workflows/go.yml` fixed it: https://github.com/jub0bs/rs-cors/actions/runs/10631782574/job/29473381691

**Pull request merged**
