### PR TITLE
Add JSON struct tags

### PR DESCRIPTION
**Pull request by mitar**
To allow to marshal options to JSON. It allows me to have a config file.

### CODE REVIEW

**Comment by jub0bs** [comment]
I'm not sure rs/cors should commit to adding JSON (un)marshaling. One issue is that different people may prefer different names for the JSON field tags, or may prefer YAML or some other format.

If needed, you could always write some glue code to translate your own struct type with JSON struct-field tags to `cors.Options`.

**Comment by rs** [comment]
I agree, the option struct is not fully JSON serializable due to incompatible types like functions. A caller is better to use an intermediate struct to store those options rather than storing them directly.

**Comment by mitar** [comment]
> This (feature creep, with longer and longer tags accommodating for JSON, YAML, TOML, and whatnot)

This is a slippery slope argument. There are few common formats and it does not mean that now there will be thousands of struct tags here.

> A caller is better to use an intermediate struct to store those options rather than storing them directly.

But why should one do an intermediate struct which would do exactly the same thing? Ignore functions (because they cannot be stored) and store other fields.

What about just adding `json:"-"` for function fields?

**Comment by jub0bs** [comment]
@mitar Coming back to an earlier comment of yours:

>  if you do prefer different names for JSON fields, then you cannot even do JSON marshal currently. Adding json tags is pretty common in various libraries, even if names case is not perfect for you at least you can use JSON marshal.

JSON (un)marshaling is in fact already possible (at least for fields that are not function-typed) if you're happy for the field names in the JSON object to match those in the declaration of the `cors.Options` struct type:

```go
var opts cors.Options
const raw = `{"AllowedOrigins":["https://example.com"]}`
dec := json.NewDecoder(strings.NewReader(raw))
if err := dec.Decode(&opts); err != nil {
  log.Fatal(err)
}
fmt.Println(opts.AllowedOrigins) // [https://example.com]
```

([playground](https://go.dev/play/p/X2a281eRuxc))

This PR may in fact break other people's code that relies on this functionality.

**Comment by mitar** [comment]
> JSON (un)marshaling is in fact already possible

Marshaling is not possible. Unmarshaling.

> This PR may in fact break existing code that relies on this functionality.

No, because JSON unmarshaling in Go is case insensitive.

**Comment by jub0bs** [comment]
@mitar 

> Marshaling is not possible.

True, marshaling is not possible, precisely because of those function-typed fields. But why do you need to marshal a CORS config to JSON? For logging purposes? My assumption is that the need for JSON unmarshaling is much more common than that for JSON marshaling...

> No, because JSON unmarshaling in Go is case insensitive.

I'm not following your reasoning. But consider [the following example](https://go.dev/play/p/Z6YoWroSTYa):

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"strings"
)

type Options struct {
	AllowedOrigins []string // `json:"allowed_origins"`
}

func main() {
	var opts Options
	const raw = `{"AllowedOrigins":["https://example.com"]}`
	dec := json.NewDecoder(strings.NewReader(raw))
	if err := dec.Decode(&opts); err != nil {
		log.Fatal(err)
	}
	fmt.Println(opts.AllowedOrigins)
}
```

If you don't modify the program, the output is

```text
[https://example.com]
```

Existing code may rely on this behavior. But such code would be broken if a field tag like `\`json:"allowed_origins"\`` were added in the declaration of the `Options` struct type. The output would indeed become:

```text
[]
```

Are you following me? If so, do you not agree that this change in behavior would be problematic?

**Comment by mitar** [comment]
You said:

> This PR may in fact break existing code that relies on this functionality.

And then provided example:

```
AllowedOrigins []string // `json:"allowed_origins"`
```

But that is a straw man fallacy. Because this PR proposes:

```
AllowedOrigins []string `json:"allowedOrigins,omitempty"`
```

How does this PR break existing code? I agree that existing code could be broken by doing things differently, but this PR does not do so. It just adds/simplifies the common case (using JSON to marshal/unmarshal) using idiomatic and backwards compatible JSON casing without breaking anything.  For anyone else who needs something differently, they should still make a proxy struct. But not sure why not add this PR for those who need the common case.

**Comment by jub0bs** [comment]
Fair enough about `allowedOrigins` being case-insensitively equal to `AllowedOrigins`; I had missed that detail.

That said, I remain unconvinced that this PR should be accepted, but the decision does not rest with me.

**Comment by rs** [comment]
I agree with @jub0bs, and I won't accept the PR. No offense intended.

**Comment by mitar** [comment]
Sounds good. No offense taken. :-)

Thank you for great package.

**Pull request closed without merging**
